"""Git operations for MCP Git Server"""

from .models import (
    GitAbort,
    GitAdd,
    GitCheckout,
    GitCherryPick,
    GitCommit,
    GitContinue,
    GitCreateBranch,
    GitDiff,
    GitDiffBranches,
    GitDiffStaged,
    GitDiffUnstaged,
    GitInit,
    GitLog,
    GitMerge,
    GitPull,
    GitPush,
    GitRebase,
    GitReset,
    GitSecurityEnforce,
    GitSecurityValidate,
    GitShow,
    GitStatus,
)
from .operations import (
    git_abort,
    git_add,
    git_checkout,
    git_cherry_pick,
    git_commit,
    git_continue,
    git_create_branch,
    git_diff,
    git_diff_branches,
    git_diff_staged,
    git_diff_unstaged,
    git_init,
    git_log,
    git_merge,
    git_pull,
    git_push,
    git_rebase,
    git_reset,
    git_show,
    git_status,
)
from .security import enforce_secure_git_config, validate_git_security_config

__all__ = [
    # Core git operations
    "git_abort",
    "git_add",
    "git_checkout",
    "git_cherry_pick",
    "git_commit",
    "git_continue",
    "git_create_branch",
    "git_diff",
    "git_diff_branches",
    "git_diff_staged",
    "git_diff_unstaged",
    "git_init",
    "git_log",
    "git_merge",
    "git_pull",
    "git_push",
    "git_rebase",
    "git_reset",
    "git_show",
    "git_status",
    # Security operations
    "enforce_secure_git_config",
    "validate_git_security_config",
    # Models
    "GitAbort",
    "GitAdd",
    "GitCheckout",
    "GitCherryPick",
    "GitCommit",
    "GitContinue",
    "GitCreateBranch",
    "GitDiff",
    "GitDiffBranches",
    "GitDiffStaged",
    "GitDiffUnstaged",
    "GitInit",
    "GitLog",
    "GitMerge",
    "GitPull",
    "GitPush",
    "GitRebase",
    "GitReset",
    "GitSecurityEnforce",
    "GitSecurityValidate",
    "GitShow",
    "GitStatus",
]
